### ISSUE TITLE
Windows XP raise error: is not a valid Win32 application - 32 OS VS 64 binary?

### ISSUE THREAD

**Issue by fcinfo** [vorburger/MariaDB4j#141]
Windows XP sp3 x86.

org.apache.commons.exec.ExecuteException: Execution failed (Exit value: -559038737. Caused by java.io.IOException: Cannot run program "C:\statrpt\tomcat\temp\MariaDB4j\base\bin\mysql_install_db.exe" (in directory "C:\statrpt\tomcat\temp\MariaDB4j\base"): CreateProcess error=193, %1 is not a valid Win32 application。)
	at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:205)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Cannot run program "C:\statrpt\tomcat\temp\MariaDB4j\base\bin\mysql_install_db.exe" (in directory "C:\statrpt\tomcat\temp\MariaDB4j\base"): CreateProcess error=193, %1 is not a valid Win32 application。
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.apache.commons.exec.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:61)
	at org.apache.commons.exec.DefaultExecutor.launch(DefaultExecutor.java:279)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:336)
	at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:48)
	at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:200)
	... 1 more
Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 7 more

**Comment by vorburger** [comment]
Not sure but this could mean you are trying to run the 64bit MariaDB binary that is packaged by this project on an old still 32bit Windows XP ? If that is the case, then you / someone would have to raise a PR to contribute a 32bit MariaDB binary to be able to fix this.
