### ISSUE TITLE
mysql: error while loading shared libraries: libnsl.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by vorburger** [vorburger/MariaDB4j#156]
The current master branch does not build for me locally anymore, due to the error in title seen below.

As it passes on TravisCI, I suspect this may have more to do with my Fedora 28 than MariaDB4j...

Still would have to fix this in order to be able to cut new releases. No time to dig into it now. Ideas welcome.

Conceptually similar problem to earlier #93 and #74 ...

```
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ mariaDB4j ---
[INFO] Surefire report directory: /home/vorburger/dev/MariaDB4j/git/MariaDB4j/mariaDB4j/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running ch.vorburger.mariadb4j.tests.MariaDB4jSampleOtherTest
(...)
[main] ERROR ch.vorburger.exec.ManagedProcess - Program [/tmp/MariaDB4j/base/bin/mysql, --socket=/tmp/MariaDB4j.44091.sock] (in working directory /tmp/MariaDB4j/base) failed
[Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mysqld: 2018-08-20 18:10:46 140082859210496 [Note] /tmp/MariaDB4j/base/bin/mysqld (unknown): Normal shutdown
[Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mysqld: 
[Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mysqld: 2018-08-20 18:10:46 140082094794496 [Note] InnoDB: FTS optimize thread exiting.
[Exec Default Executor] INFO ch.vorburger.exec.ManagedProcess - Program [/tmp/MariaDB4j/base/bin/mysqld, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M, --basedir=/tmp/MariaDB4j/base, --datadir=/tmp/MariaDB4j/data/44091, --port=44091, --socket=/tmp/MariaDB4j.44091.sock] (in working directory /tmp/MariaDB4j/base) just exited, with value 0
[main] INFO ch.vorburger.exec.ManagedProcess - Successfully destroyed Program [/tmp/MariaDB4j/base/bin/mysqld, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M, --basedir=/tmp/MariaDB4j/base, --datadir=/tmp/MariaDB4j/data/44091, --port=44091, --socket=/tmp/MariaDB4j.44091.sock] (in working directory /tmp/MariaDB4j/base)
[main] INFO ch.vorburger.mariadb4j.DB - Database stopped.
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 8.003 sec <<< FAILURE!
sqlDump(ch.vorburger.mariadb4j.tests.MariaDB4jSampleDumpTest)  Time elapsed: 3.971 sec  <<< ERROR!
ch.vorburger.exec.ManagedProcessException: An error occurred while running a command: create database if not exists `planetexpress`;
	at ch.vorburger.mariadb4j.DB.run(DB.java:296)
	at ch.vorburger.mariadb4j.DB.run(DB.java:265)
	at ch.vorburger.mariadb4j.DB.run(DB.java:269)
	at ch.vorburger.mariadb4j.DB.createDB(DB.java:304)
	at ch.vorburger.mariadb4j.tests.MariaDB4jSampleDumpTest.beforeTest(MariaDB4jSampleDumpTest.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: ch.vorburger.exec.ManagedProcessException: Program [/tmp/MariaDB4j/base/bin/mysql, --socket=/tmp/MariaDB4j.44727.sock] (in working directory /tmp/MariaDB4j/base) failed, exitValue=-559038737, last 100 lines of console:
/tmp/MariaDB4j/base/bin/mysql: error while loading shared libraries: libnsl.so.1: cannot open shared object file: No such file or directory
	at ch.vorburger.exec.ManagedProcess.checkResult(ManagedProcess.java:295)
	at ch.vorburger.exec.ManagedProcess.startExecute(ManagedProcess.java:205)
	at ch.vorburger.exec.ManagedProcess.start(ManagedProcess.java:144)
	at ch.vorburger.mariadb4j.DB.run(DB.java:293)
	... 34 more
Caused by: org.apache.commons.exec.ExecuteException: Execution failed (Exit value: -559038737. Caused by java.io.IOException: Stream closed)
	at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:205)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Stream closed
	at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
	at java.io.OutputStream.write(OutputStream.java:116)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
	at org.apache.commons.exec.DefaultExecutor.closeProcessStreams(DefaultExecutor.java:306)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:387)
	at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:48)
	at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:200)
	... 1 more

xmlDump(ch.vorburger.mariadb4j.tests.MariaDB4jSampleDumpTest)  Time elapsed: 4.021 sec  <<< ERROR!
ch.vorburger.exec.ManagedProcessException: An error occurred while running a command: create database if not exists `planetexpress`;
	at ch.vorburger.mariadb4j.DB.run(DB.java:296)
	at ch.vorburger.mariadb4j.DB.run(DB.java:265)
	at ch.vorburger.mariadb4j.DB.run(DB.java:269)
	at ch.vorburger.mariadb4j.DB.createDB(DB.java:304)
	at ch.vorburger.mariadb4j.tests.MariaDB4jSampleDumpTest.beforeTest(MariaDB4jSampleDumpTest.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: ch.vorburger.exec.ManagedProcessException: Program [/tmp/MariaDB4j/base/bin/mysql, --socket=/tmp/MariaDB4j.44091.sock] (in working directory /tmp/MariaDB4j/base) failed, exitValue=-559038737, last 100 lines of console:
/tmp/MariaDB4j/base/bin/mysql: error while loading shared libraries: libnsl.so.1: cannot open shared object file: No such file or directory
	at ch.vorburger.exec.ManagedProcess.checkResult(ManagedProcess.java:295)
	at ch.vorburger.exec.ManagedProcess.startExecute(ManagedProcess.java:205)
	at ch.vorburger.exec.ManagedProcess.start(ManagedProcess.java:144)
	at ch.vorburger.mariadb4j.DB.run(DB.java:293)
	... 34 more
Caused by: org.apache.commons.exec.ExecuteException: Execution failed (Exit value: -559038737. Caused by java.io.IOException: Stream closed)
	at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:205)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Stream closed
	at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
	at java.io.OutputStream.write(OutputStream.java:116)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
	at org.apache.commons.exec.DefaultExecutor.closeProcessStreams(DefaultExecutor.java:306)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:387)
	at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:48)
	at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:200)
	... 1 more

(...)

Results :

Tests in error: 
  testEmbeddedMariaDB4jWithSecurity(ch.vorburger.mariadb4j.tests.MariaDB4jSampleTutorialTest): An error occurred while running a command: create database if not exists `mariaDB4jTestWSecurity`;
  testEmbeddedMariaDB4j(ch.vorburger.mariadb4j.tests.MariaDB4jSampleTutorialTest): An error occurred while running a command: create database if not exists `mariaDB4jTest`;
  validateSourceInitialization(ch.vorburger.mariadb4j.tests.junit.MariaDB4jUnitRuleInitDBTest): An error occurred while running a command: create database if not exists `junittest`;
  sqlDump(ch.vorburger.mariadb4j.tests.MariaDB4jSampleDumpTest): An error occurred while running a command: create database if not exists `planetexpress`;
  xmlDump(ch.vorburger.mariadb4j.tests.MariaDB4jSampleDumpTest): An error occurred while running a command: create database if not exists `planetexpress`;

Tests run: 17, Failures: 0, Errors: 5, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] mariaDB4j-pom ...................................... SUCCESS [  2.826 s]
[INFO] mariaDB4j-core ..................................... SUCCESS [  4.273 s]
[INFO] mariaDB4j (all-in-one artifact) .................... FAILURE [01:13 min]
[INFO] mariaDB4j-app ...................................... SKIPPED
[INFO] mariaDB4j-maven-plugin ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:21 min
[INFO] Finished at: 2018-08-20T18:11:07+02:00
[INFO] Final Memory: 37M/650M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project mariaDB4j: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/vorburger/dev/MariaDB4j/git/MariaDB4j/mariaDB4j/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :mariaDB4j
```

**Comment by vorburger** [comment]
@duttonw are you a Linux user and want to help figure out what package I need to install to fix this? :smile:

**Comment by vorburger** [comment]
Duh - I'm getting old, forgetting that I myself [previously documented in the FAQ how to solve such issues](https://github.com/vorburger/MariaDB4j/#faq):

```
$ sudo dnf provides libnsl.so.1
libnsl-2.27-30.fc28.i686 : Legacy support library for NIS
Repo        : updates
Matched from:
Provide    : libnsl.so.1

libnsl-2.27-8.fc28.i686 : Legacy support library for NIS
Repo        : fedora
Matched from:
Provide    : libnsl.so.1

$ sudo dnf install libnsl.so.1
```

This should fix the problem - but doesn't for me... does this need a cold OS restart??

**Comment by vorburger** [comment]
> This should fix the problem - but doesn't for me... does this need a cold OS restart??

Nope, that doesn't help... so the problem is with the `mysql` client (not `mysqld`), and simple to reproduce:

    $ chmod +x DBs/mariaDB4j-db-linux64-10.2.11/target/classes/ch/vorburger/mariadb4j/mariadb-10.2.11/linux/bin/mysql 
    $ ./DBs/mariaDB4j-db-linux64-10.2.11/target/classes/ch/vorburger/mariadb4j/mariadb-10.2.11/linux/bin/mysql 
    ./DBs/mariaDB4j-db-linux64-10.2.11/target/classes/ch/vorburger/mariadb4j/mariadb-10.2.11/linux/bin/mysql: error while loading shared libraries: libnsl.so.1: cannot open shared object file: No such file or directory

I'm guessing despite `libnsl.so.1` being installed, it's not on that "library path"thing - how did that stuff work again, anyone knows?

**Comment by duttonw** [comment]
on my mac i can build. I'll try a couple more systems when i have time.

**Comment by vorburger** [comment]
> Conceptually similar problem to earlier #93 and #74 ...
> so the problem is with the mysql client (not mysqld)

which makes me wonder if perhaps instead of spawning (exec) `mysql` we couldn't just use JDBC to do `create database` and what not... anyone interested in working on this?

**Comment by vorburger** [comment]
Funny, it now works again for me locally; I must have recently installed some RPM package which provides what was missing .. a better longer term solution to (all these) problem/s would be to not launch an external `mysql`client for `run()` and `source()`, but execute JDBC statements via JDBC?

**Comment by FlorianSchaetz** [comment]
Just a detail... The problem seems also to happen if you set lib AND base directory in the config. If I only set base and data directory, everything runs fine, but if I add the lib directory to the config, it dies with the "error while loading shared libraries:" error.

**Comment by vorburger** [comment]
@FlorianSchaetz if you can raise a PR with a fix, or just a failing test illustrating this problem, then perhaps someone would like to look at contributing a fix for what you hav run into.

**Comment by rkraneis** [comment]
On CentOS 8 we needed to locally install ``libnsl`` (Legacy support library for NIS) for ``libnsl.so.1`` as well as ``ncurses-compat-libs`` (Ncurses compatibility libraries) for ``libncurses.so.5``. We only set tempDir using obsolete ``com.github.mike10004`` maven plugin (up-to-date one is missing the port goal).

**Comment by elfrancisco** [comment]
This has solved the problem for me:
sudo dnf install libnsl

**Comment by vorburger** [comment]
FTR: #1120 is related to and follows-up on this problem.
