### ISSUE TITLE
mariaDB4j-maven-plugin is broken on master

### ISSUE THREAD

**Issue by vorburger** [vorburger/MariaDB4j#207]
`mvn clean install` on current master fails due to:

```
[INFO] --- maven-invoker-plugin:3.2.0:install (prepare-integration-test) @ mariaDB4j-maven-plugin ---
(...)
[INFO] [INFO] --- mariaDB4j-maven-plugin:2.3.1-SNAPSHOT:stop (post-integration-test) @ start-stop ---
[INFO] [INFO] Stopping MariaDB4j...
[INFO] [INFO] mysqld: 2019-02-11 20:37:37 139736656480000 [Note] /tmp/MariaDB4j/base/bin/mysqld (unknown): Normal shutdown
[INFO] [INFO] mysqld: 
[INFO] [INFO] mysqld: 2019-02-11 20:37:37 139736207316736 [Note] InnoDB: FTS optimize thread exiting.
[INFO] [INFO] Program [/tmp/MariaDB4j/base/bin/mysqld, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M, --basedir=/tmp/MariaDB4j/base, --datadir=/tmp/MariaDB4j/data/45257, --port=45257, --socket=/tmp/MariaDB4j.45257.sock] (in working directory /tmp/MariaDB4j/base) just exited, with value 0
[INFO] [INFO] Successfully destroyed Program [/tmp/MariaDB4j/base/bin/mysqld, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M, --basedir=/tmp/MariaDB4j/base, --datadir=/tmp/MariaDB4j/data/45257, --port=45257, --socket=/tmp/MariaDB4j.45257.sock] (in working directory /tmp/MariaDB4j/base)
[INFO] [INFO] Database stopped.
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] BUILD SUCCESS
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] Total time: 14.155 s
[INFO] [INFO] Finished at: 2019-02-11T20:37:39+01:00
[INFO] [INFO] Final Memory: 18M/352M
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] cleanupOnExit() ShutdownHook quietly deleting temporary DB data directory: /tmp/MariaDB4j/data/45257
[INFO] Exception in thread "Shutdown Hook Deletion Thread for Temporary DB /tmp/MariaDB4j/data/45257" java.lang.NoClassDefFoundError: org/apache/commons/io/FilenameUtils
[INFO] 	at org.apache.commons.io.FileUtils.isSymlink(FileUtils.java:2753)
[INFO] 	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1466)
[INFO] 	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2183)
[INFO] 	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1585)
[INFO] 	at org.apache.commons.io.FileUtils.deleteQuietly(FileUtils.java:1498)
[INFO] 	at ch.vorburger.mariadb4j.DB$1.run(DB.java:405)
[INFO] Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.FilenameUtils
[INFO] 	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
[INFO] 	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
[INFO] 	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
[INFO] 	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
[INFO] 	... 6 more
[INFO] run post-build script verify.groovy
[INFO] Running post-build script: /home/vorburger/dev/MariaDB4j/git/MariaDB4j/mariaDB4j-maven-plugin/target/it/start-stop/verify.groovy
[INFO]   The post-build script did not succeed. MariaDB4j should have run
[INFO]           start-stop/pom.xml ............................... FAILED (15.8 s)
[INFO] Building: start-stop-skip/pom.xml
[INFO] [INFO] Scanning for projects...
[INFO] [INFO] 
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] Building start-stop-skip 0.0.1.BUILD-SNAPSHOT
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] 
[INFO] [INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ start-stop-skip ---
[INFO] [INFO] 
[INFO] [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ start-stop-skip ---
[INFO] [INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] [INFO] skip non existing resourceDirectory /home/vorburger/dev/MariaDB4j/git/MariaDB4j/mariaDB4j-maven-plugin/target/it/start-stop-skip/src/main/resources
[INFO] [INFO] 
[INFO] [INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ start-stop-skip ---
[INFO] [INFO] No sources to compile
[INFO] [INFO] 
[INFO] [INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ start-stop-skip ---
[INFO] [INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] [INFO] skip non existing resourceDirectory /home/vorburger/dev/MariaDB4j/git/MariaDB4j/mariaDB4j-maven-plugin/target/it/start-stop-skip/src/test/resources
[INFO] [INFO] 
[INFO] [INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ start-stop-skip ---
[INFO] [INFO] No sources to compile
[INFO] [INFO] 
[INFO] [INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ start-stop-skip ---
[INFO] [INFO] No tests to run.
[INFO] [INFO] 
[INFO] [INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ start-stop-skip ---
[INFO] [WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] [INFO] Building jar: /home/vorburger/dev/MariaDB4j/git/MariaDB4j/mariaDB4j-maven-plugin/target/it/start-stop-skip/target/start-stop-skip-0.0.1.BUILD-SNAPSHOT.jar
[INFO] [INFO] 
[INFO] [INFO] --- mariaDB4j-maven-plugin:2.3.1-SNAPSHOT:start (pre-integration-test) @ start-stop-skip ---
[INFO] [INFO] 
[INFO] [INFO] --- mariaDB4j-maven-plugin:2.3.1-SNAPSHOT:stop (post-integration-test) @ start-stop-skip ---
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] BUILD SUCCESS
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] Total time: 2.197 s
[INFO] [INFO] Finished at: 2019-02-11T20:37:43+01:00
[INFO] [INFO] Final Memory: 14M/370M
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] run post-build script verify.groovy
[INFO] Running post-build script: /home/vorburger/dev/MariaDB4j/git/MariaDB4j/mariaDB4j-maven-plugin/target/it/start-stop-skip/verify.groovy
[INFO] Finished post-build script: /home/vorburger/dev/MariaDB4j/git/MariaDB4j/mariaDB4j-maven-plugin/target/it/start-stop-skip/verify.groovy
[INFO]           start-stop-skip/pom.xml .......................... SUCCESS (3.9 s)
[INFO] -------------------------------------------------
[INFO] Build Summary:
[INFO]   Passed: 1, Failed: 2, Errors: 0, Skipped: 0
[INFO] -------------------------------------------------
[ERROR] The following builds failed:
[ERROR] *  mariadb4j-maven-plugin-test-basic/pom.xml
[ERROR] *  start-stop/pom.xml
[INFO] -------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] mariaDB4j-pom ...................................... SUCCESS [  2.828 s]
[INFO] mariaDB4j-core ..................................... SUCCESS [  4.858 s]
[INFO] mariaDB4j (all-in-one artifact) .................... SUCCESS [02:01 min]
[INFO] mariaDB4j-springboot ............................... SUCCESS [ 17.423 s]
[INFO] mariaDB4j-app ...................................... SUCCESS [ 38.175 s]
[INFO] mariaDB4j-maven-plugin ............................. FAILURE [01:22 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:28 min
[INFO] Finished at: 2019-02-11T20:37:44+01:00
[INFO] Final Memory: 82M/823M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-invoker-plugin:3.2.0:run (integration-test) on project mariaDB4j-maven-plugin: 2 builds failed. See console output above for details. -> [Help 1]
```

**Comment by vorburger** [comment]
I currently have this `mvn`, just in case this matters:

    Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T09:58:13+02:00

**Comment by vorburger** [comment]
I've locally reverted fb4fe06ed73ebf7eac311fc38f5ed7a733b8a26c and  4e398139e79b46e094e61c20f9018423c5953111 and neither of those was the culprit (still broken even without those). 

I'll keep digging... @duttonw if you have any clue, feel free to jump in here...

**Comment by vorburger** [comment]
So `FilenameUtils` itself is never directly used in MariaDB4j code, but `FileUtils.deleteQuietly` calls it, and somehow another version than the we use ends up on the `mariaDB4j-maven-plugin` classpath...

**Comment by vorburger** [comment]
0ff7e5b50cb775bb1daf54bd245f127209282361 seems to fix the problem re. commons-io, but I'm hitting 2 new issues new... :-( @duttonw you sure this mariaDB4j-maven-plugin actually ever passed the build? Just joking, perhaps depends on Maven version, or something.

**Comment by sherrif10** [comment]
Hey vorburger, did we fix this error, if so any guidance or link to point me to this solution thanks
