### ISSUE TITLE
MariaDB4j doesn't work with the version 2.4.0

### ISSUE THREAD

**Issue by fabien91** [vorburger/MariaDB4j#217]
Hello,

Today, i've tried to update mariadb4j from 2.3.0 to 2.4.0, and now i have this errors :

https://pastebin.com/2tsBwvYT

Could you help me please ?

Thanks
Fabien

**Comment by vorburger** [comment]
```
[main] INFO ch.vorburger.mariadb4j.Util - Created directory: C:\Users\Fabien\AppData\Local\Temp\MariaDB4j\data\3251
getFirstUser(fr.just2craft.MineCore.test.mysql.MySQL_Test)  Time elapsed: 3.948 sec  <<< ERROR!
java.lang.AbstractMethodError: org.apache.logging.log4j.core.config.ConfigurationFactory.getConfiguration(Lorg/apache/logging/log4j/core/LoggerContext;Lorg/apache/logging/log4j/core/config/ConfigurationSource;)Lorg/apache/logging/log4j/core/config/Configuration;
    at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:522)
    at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:459)
    at org.apache.logging.log4j.core.config.ConfigurationFactory.getConfiguration(ConfigurationFactory.java:265)
    at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:613)
    at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:634)
    at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:229)
    at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:152)
    at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
    at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
    at org.apache.commons.logging.LogAdapter$Log4jLog.<clinit>(LogAdapter.java:155)
    at org.apache.commons.logging.LogAdapter$Log4jAdapter.createLog(LogAdapter.java:122)
    at org.apache.commons.logging.LogAdapter.createLog(LogAdapter.java:89)
    at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:67)
    at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:59)
    at org.springframework.core.io.support.PathMatchingResourcePatternResolver.<clinit>(PathMatchingResourcePatternResolver.java:185)
    at ch.vorburger.mariadb4j.Util.extractFromClasspathToFile(Util.java:118)
    at ch.vorburger.mariadb4j.DB.unpackEmbeddedDb(DB.java:345)
    at ch.vorburger.mariadb4j.DB.newEmbeddedDB(DB.java:80)
    at ch.vorburger.mariadb4j.DB.newEmbeddedDB(DB.java:97)
    at fr.just2craft.MineCore.test.mysql.MySQL_Test.setUp(MySQL_Test.java:38
```

**Comment by vorburger** [comment]
This means that you have some version conflict on log4j - like MariaDB4j wants one, Spring another, your project may specify another in your Maven POM or Gradle or whatever you use... you have to check all those to make them "converge". Best of luck!
