### ISSUE TITLE
Error while running parallel Gradle tests. 

### ISSUE THREAD

**Issue by davinchia** [vorburger/MariaDB4j#244]
Hi,

First off, great project! We are currently migrating to a monorepo and MariaDB4J has been very helpful in speeding up builds.

From time to time we do see the following error when running tests in parallel. Its worthy to note this only happens on the ubuntu distro. This is on MariaDB4J `2.4.0`.
```
com.rapleaf.jack.exception.ConnectionCreationFailureException: DB connection creation failed
	at com.rapleaf.jack.transaction.DbPoolManager.getConnection(DbPoolManager.java:111)
	at com.rapleaf.jack.transaction.TransactorImpl.execute(TransactorImpl.java:102)
	at com.rapleaf.jack.transaction.TransactorImpl.execute(TransactorImpl.java:55)
	at com.liveramp.file_deliverer.TestDeliveryModelsManager.setUp(TestDeliveryModelsManager.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: ch.vorburger.exec.ManagedProcessException: An error occurred while running a command: create database if not exists `distribution_db`;
	at com.liveramp.mariadb_test_lib.shared.MariaDatabasesImpl.getDb(MariaDatabasesImpl.java:36)
	at com.liveramp.mariadb_test_lib.shared.MariaDatabasesImpl.lambda$getDbTransactor$0(MariaDatabasesImpl.java:43)
	at com.rapleaf.jack.transaction.DbPoolManager$DbPoolFactory.makeObject(DbPoolManager.java:162)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:868)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:435)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
	at com.rapleaf.jack.transaction.DbPoolManager.getConnection(DbPoolManager.java:97)
	... 50 more
Caused by: java.lang.RuntimeException: ch.vorburger.exec.ManagedProcessException: An error occurred while running a command: create database if not exists `distribution_db`;
	at com.liveramp.mariadb_test_lib.databases.DistMariaDb$DistMariaDbSingletonProvider.create(DistMariaDb.java:37)
	at com.liveramp.mariadb_test_lib.databases.DistMariaDb$DistMariaDbSingletonProvider.create(DistMariaDb.java:23)
	at com.liveramp.java_support.factories.LazyLoadingSingletonFactory.get(LazyLoadingSingletonFactory.java:12)
	at com.liveramp.mariadb_test_lib.shared.MariaDatabasesImpl.getDb(MariaDatabasesImpl.java:33)
	... 56 more
Caused by: ch.vorburger.exec.ManagedProcessException: An error occurred while running a command: create database if not exists `distribution_db`;
	at ch.vorburger.mariadb4j.DB.run(DB.java:300)
	at ch.vorburger.mariadb4j.DB.run(DB.java:265)
	at ch.vorburger.mariadb4j.DB.run(DB.java:269)
	at ch.vorburger.mariadb4j.DB.createDB(DB.java:308)
	at com.liveramp.mariadb_test_lib.databases.DistMariaDb$DistMariaDbSingletonProvider.create(DistMariaDb.java:32)
	... 59 more
Caused by: ch.vorburger.exec.ManagedProcessException: Asked to waitFor Program [/tmp/MariaDB4j/base/e2231eba-b480-4f42-8eee-32f66ad88e15/bin/mysql, --socket=/tmp/MariaDB4j.39701.sock] (in working directory /tmp/MariaDB4j/base/e2231eba-b480-4f42-8eee-32f66ad88e15), but it was never even start()'ed!
	at ch.vorburger.exec.ManagedProcess.assertWaitForIsValid(ManagedProcess.java:478)
	at ch.vorburger.exec.ManagedProcess.waitForExitMaxMsWithoutLog(ManagedProcess.java:439)
	at ch.vorburger.exec.ManagedProcess.waitForExit(ManagedProcess.java:418)
	at ch.vorburger.mariadb4j.DB.run(DB.java:298)
	... 63 more
```

I've poked around abit, but aren't really sure where to begin. Any hints pointing me in the right direction would be very helpful.

Thanks,
Davin

**Comment by vorburger** [comment]
It's difficult to tell, from above.

The best you can do is further debug it yourself.

**Comment by LeboyX** [comment]
I see this error, sporadically, when running integration tests on my Windows 10 machine. I'm using MariaDB4j version 2.5.3, as it's the latest version that support my Java version (8). I'm not running my tests in parallel. No particular test always fails; any of my tests could fail b/c the process was `never even start()'ed!`. 

For reference, here's the stack of my error:
```
    lbx.common.exception.LbxRuntimeException: ch.vorburger.exec.ManagedProcessException: An error occurred while running a command: create database if not exists `lbxdb`;
        at lbx.common.exception.LbxRuntimeException.wrap(LbxRuntimeException.java:27)
        at lbx.db.LbxMariaDbRule$DbFrame.initDB(LbxMariaDbRule.java:126)
        at lbx.db.LbxMariaDbRule$DbFrame.lambda$new$0(LbxMariaDbRule.java:102)
        at lbx.common.util.impl.LbxLazy.demand(LbxLazy.java:115)
        at lbx.db.LbxMariaDbRule$DbFrame.push(LbxMariaDbRule.java:107)
        at lbx.context.impl.SimpleLbxContextStack.push(SimpleLbxContextStack.java:69)
        at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at lbx.common.util.LbxDeferred.lambda$proxy$0(LbxDeferred.java:65)
        at com.sun.proxy.$Proxy11.push(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at lbx.common.util.LbxDeferred.lambda$proxy$0(LbxDeferred.java:65)
        at com.sun.proxy.$Proxy11.push(Unknown Source)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at lbx.context.impl.SimpleLbxCtxtStackRunner.lambda$runR$2(SimpleLbxCtxtStackRunner.java:171)
        at lbx.context.impl.LocalLbxCtxtStackRunner$Builder.lambda$new$0(LocalLbxCtxtStackRunner.java:214)
        at lbx.context.impl.SimpleLbxCtxtStackRunner.runR(SimpleLbxCtxtStackRunner.java:158)
        at lbx.context.impl.SimpleLbxCtxtStackRunner.run(SimpleLbxCtxtStackRunner.java:123)
        at lbx.context.impl.LocalLbxCtxtStackRunner$Builder.run(LocalLbxCtxtStackRunner.java:319)
        at lbx.db.LbxMariaDbRule$1.evaluate(LbxMariaDbRule.java:61)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
        at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
        at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)

        Caused by:
        ch.vorburger.exec.ManagedProcessException: An error occurred while running a command: create database if not exists `lbxdb`;
            at ch.vorburger.mariadb4j.DB.run(DB.java:371)
            at ch.vorburger.mariadb4j.DB.run(DB.java:334)
            at ch.vorburger.mariadb4j.DB.run(DB.java:313)
            at ch.vorburger.mariadb4j.DB.run(DB.java:317)
            at ch.vorburger.mariadb4j.DB.createDB(DB.java:377)
            at lbx.db.LbxMariaDbRule$DbFrame.initDB(LbxMariaDbRule.java:122)
            ... 47 more

            Caused by:
            ch.vorburger.exec.ManagedProcessException: Asked to waitFor Program [C:\Users\ERICLI~1\AppData\Local\Temp\MariaDB4j\base\bin\mysql.exe, --port=54166] (in working directory C:\Users\ERICLI~1\AppData\Local\Temp\MariaDB4j\base), but it was never even start()'ed!
                at ch.vorburger.exec.ManagedProcess.assertWaitForIsValid(ManagedProcess.java:477)
                at ch.vorburger.exec.ManagedProcess.waitForExitMaxMsWithoutLog(ManagedProcess.java:437)
                at ch.vorburger.exec.ManagedProcess.waitForExit(ManagedProcess.java:416)
                at ch.vorburger.mariadb4j.DB.run(DB.java:369)
```

I noticed that the DB spawns a process and then waits for 100ms, but the comments didn't make it clear why it was waiting. It is possible, then, for this code to blow up if it takes longer than 100ms for the process to fire up?
