### ISSUE TITLE
The cleanupOnExit ShutdownHook should not log warnings if directory does not exists

### ISSUE THREAD

**Issue by akkie** [vorburger/MariaDB4j#26]
The `cleanupOnExit()` ShutdownHook logs warnings if the directory, it tries to delete, does not exists anymore. Currently I get warnings in my log, also if the directories doesn't exists.
```
[warn] c.v.m.DB - cleanupOnExit() ShutdownHook: An error occurred while deleting a directory
java.io.IOException: Unable to delete directory /tmp/MariaDB4j/data/3333.
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1541) ~[commons-io-2.4.jar:2.4]
	at ch.vorburger.mariadb4j.DB$1.run(DB.java:336) ~[mariaDB4j-2.1.3.jar:na]
[warn] c.v.m.DB - cleanupOnExit() ShutdownHook: An error occurred while deleting a directory
java.io.IOException: Unable to delete directory /tmp/MariaDB4j/data/3333.
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1541) ~[commons-io-2.4.jar:2.4]
	at ch.vorburger.mariadb4j.DB$1.run(DB.java:336) ~[mariaDB4j-2.1.3.jar:na]
[warn] c.v.m.DB - cleanupOnExit() ShutdownHook: An error occurred while deleting a directory
java.io.IOException: Unable to delete file: /tmp/MariaDB4j/base/share/norwegian/errmsg.sys
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2279) ~[commons-io-2.4.jar:2.4]
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653) ~[commons-io-2.4.jar:2.4]
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535) ~[commons-io-2.4.jar:2.4]
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270) ~[commons-io-2.4.jar:2.4]
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653) ~[commons-io-2.4.jar:2.4]
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535) ~[commons-io-2.4.jar:2.4]
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270) ~[commons-io-2.4.jar:2.4]
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653) ~[commons-io-2.4.jar:2.4]
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535) ~[commons-io-2.4.jar:2.4]
	at ch.vorburger.mariadb4j.DB$1.run(DB.java:340) ~[mariaDB4j-2.1.3.jar:na]
[warn] c.v.m.DB - cleanupOnExit() ShutdownHook: An error occurred while deleting a directory
java.io.IOException: Unable to delete directory /tmp/MariaDB4j/base/share.
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1541) ~[commons-io-2.4.jar:2.4]
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270) ~[commons-io-2.4.jar:2.4]
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653) ~[commons-io-2.4.jar:2.4]
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535) ~[commons-io-2.4.jar:2.4]
	at ch.vorburger.mariadb4j.DB$1.run(DB.java:340) ~[mariaDB4j-2.1.3.jar:na]
[warn] c.v.m.DB - cleanupOnExit() ShutdownHook: An error occurred while deleting a directory
java.io.IOException: Unable to delete file: /tmp/MariaDB4j/base/share/swedish/errmsg.sys
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2279) ~[commons-io-2.4.jar:2.4]
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653) ~[commons-io-2.4.jar:2.4]
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535) ~[commons-io-2.4.jar:2.4]
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270) ~[commons-io-2.4.jar:2.4]
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653) ~[commons-io-2.4.jar:2.4]
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535) ~[commons-io-2.4.jar:2.4]
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270) ~[commons-io-2.4.jar:2.4]
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653) ~[commons-io-2.4.jar:2.4]
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535) ~[commons-io-2.4.jar:2.4]
	at ch.vorburger.mariadb4j.DB$1.run(DB.java:340) ~[mariaDB4j-2.1.3.jar:na]
```

**Comment by vorburger** [comment]
Agreed, and probably very easy to fix.. Do you want to send me a PR about
this? I would merge it ASAP.

**Comment by akkie** [comment]
@vorburger I've looked at the code and there is already a check if the directory exists. So the main problem is that the shutdown hook isn't thread safe and therefore there is a race condition between the different shutdown hooks. So maybe a synchronized block is a better fix instead of suppressing the log message. What do you think?

**Comment by vorburger** [comment]
@akkie I've changed it to deleteQuietly() instead of  deleteDirectory() and catch... makes sense to you?

PS: Sorry this one took so long! Life.
