### ISSUE TITLE
MariaDB4j does not support mysql > 5.5 ?

### ISSUE THREAD

**Issue by s50600822** [vorburger/MariaDB4j#286]
Not sure i this is due to:
https://mariadb.com/kb/en/library/mariadb-vs-mysql-compatibility/#drop-in-compatibility-of-specific-mariadb-versions

```
> Task :conductor-mysql-persistence:test
com.netflix.conductor.dao.mysql.MySQLQueueDAOTest > pollDeferredMessagesTest FAILED
    org.flywaydb.core.internal.license.FlywayEditionUpgradeRequiredException at MySQLQueueDAOTest.java:43
    java.lang.NullPointerException at MySQLQueueDAOTest.java:49
com.netflix.conductor.dao.mysql.MySQLQueueDAOTest > processUnacksTest FAILED
    org.flywaydb.core.internal.license.FlywayEditionUpgradeRequiredException at MySQLQueueDAOTest.java:43
    java.lang.NullPointerException at MySQLQueueDAOTest.java:49
com.netflix.conductor.dao.mysql.MySQLQueueDAOTest > complexQueueTest FAILED
    org.flywaydb.core.internal.license.FlywayEditionUpgradeRequiredException at MySQLQueueDAOTest.java:43
    java.lang.NullPointerException at MySQLQueueDAOTest.java:49
com.netflix.conductor.dao.mysql.MySQLQueueDAOTest > pollMessagesTest FAILED
    org.flywaydb.core.internal.license.FlywayEditionUpgradeRequiredException at MySQLQueueDAOTest.java:43
    java.lang.NullPointerException at MySQLQueueDAOTest.java:49
com.netflix.conductor.dao.mysql.MySQLMetadataDAOTest > testWorkflowDefOperations FAILED
    org.flywaydb.core.internal.license.FlywayEditionUpgradeRequiredException at MySQLMetadataDAOTest.java:40
    java.lang.NullPointerException at MySQLMetadataDAOTest.java:46
com.netflix.conductor.dao.mysql.MySQLMetadataDAOTest > testEventHandlers FAILED
    org.flywaydb.core.internal.license.FlywayEditionUpgradeRequiredException at MySQLMetadataDAOTest.java:40
    java.lang.NullPointerException at MySQLMetadataDAOTest.java:46
com.netflix.conductor.dao.mysql.MySQLMetadataDAOTest > testRemoveTaskDef FAILED
    org.flywaydb.core.internal.license.FlywayEditionUpgradeRequiredException at MySQLMetadataDAOTest.java:40
    java.lang.NullPointerException at MySQLMetadataDAOTest.java:46
com.netflix.conductor.dao.mysql.MySQLMetadataDAOTest > testDuplicate FAILED
    org.flywaydb.core.internal.license.FlywayEditionUpgradeRequiredException at MySQLMetadataDAOTest.java:40
    java.lang.NullPointerException at MySQLMetadataDAOTest.java:46
com.netflix.conductor.dao.mysql.MySQLMetadataDAOTest > testTaskDefOperations FAILED
    org.flywaydb.core.internal.license.FlywayEditionUpgradeRequiredException at MySQLMetadataDAOTest.java:40
    java.lang.NullPointerException at MySQLMetadataDAOTest.java:46
com.netflix.conductor.dao.mysql.MySQLExecutionDAOTest > testPendingByCorrelationId FAILED
    org.flywaydb.core.internal.license.FlywayEditionUpgradeRequiredException at MySQLExecutionDAOTest.java:41
    java.lang.NullPointerException at MySQLExecutionDAOTest.java:51
com.netflix.conductor.dao.mysql.MySQLExecutionDAOTest > testTaskOps FAILED
    org.flywaydb.core.internal.license.FlywayEditionUpgradeRequiredException at MySQLExecutionDAOTest.java:41
    java.lang.NullPointerException at MySQLExecutionDAOTest.java:51
com.netflix.conductor.dao.mysql.MySQLExecutionDAOTest > complexExecutionTest FAILED
    org.flywaydb.core.internal.license.FlywayEditionUpgradeRequiredException at MySQLExecutionDAOTest.java:41
    java.lang.NullPointerException at MySQLExecutionDAOTest.java:51
com.netflix.conductor.dao.mysql.MySQLExecutionDAOTest > testPending FAILED
    org.flywaydb.core.internal.license.FlywayEditionUpgradeRequiredException at MySQLExecutionDAOTest.java:41
    java.lang.NullPointerException at MySQLExecutionDAOTest.java:51
com.netflix.conductor.dao.mysql.MySQLExecutionDAOTest > testCreateTaskException FAILED
    org.flywaydb.core.internal.license.FlywayEditionUpgradeRequiredException at MySQLExecutionDAOTest.java:41
    java.lang.NullPointerException at MySQLExecutionDAOTest.java:51
com.netflix.conductor.dao.mysql.MySQLExecutionDAOTest > testTaskCreateDups FAILED
    org.flywaydb.core.internal.license.FlywayEditionUpgradeRequiredException at MySQLExecutionDAOTest.java:41
    java.lang.NullPointerException at MySQLExecutionDAOTest.java:51
com.netflix.conductor.dao.mysql.MySQLExecutionDAOTest > testCreateTaskException2 FAILED
    org.flywaydb.core.internal.license.FlywayEditionUpgradeRequiredException at MySQLExecutionDAOTest.java:41
    java.lang.NullPointerException at MySQLExecutionDAOTest.java:51
com.netflix.conductor.dao.mysql.MySQLExecutionDAOTest > testPollData FAILED
    org.flywaydb.core.internal.license.FlywayEditionUpgradeRequiredException at MySQLExecutionDAOTest.java:41
    java.lang.NullPointerException at MySQLExecutionDAOTest.java:51
com.netflix.conductor.dao.mysql.MySQLExecutionDAOTest > testTaskExceedsLimit FAILED
    org.flywaydb.core.internal.license.FlywayEditionUpgradeRequiredException at MySQLExecutionDAOTest.java:41
    java.lang.NullPointerException at MySQLExecutionDAOTest.java:51
```

https://travis-ci.org/Netflix/conductor/builds/575761793?utm_source=github_status&utm_medium=notification

<img width="1631" alt="Screen Shot 2019-08-23 at 10 46 42 pm" src="https://user-images.githubusercontent.com/5586453/63593730-ea4cb380-c5f7-11e9-9044-b8c025e46276.png">

**Comment by s50600822** [comment]
my mistake
```
  Task has failed previously.
Starting process 'Gradle Test Executor 117'. Working directory: /Users/hoaphan/dev/code/forked/conductor/mysql-persistence Command: /Users/hoaphan/.sdkman/candidates/java/8.0.222-amzn/bin/java -Djava.security.manager=worker.org.gradle.process.internal.worker.child.BootstrapSecurityManager -Dorg.gradle.native=false -javaagent:build/tmp/expandedArchives/org.jacoco.agent-0.8.1.jar_8059ed6e1ab8b88aac5d9097fad847bb/jacocoagent.jar=destfile=build/jacoco/test.exec,append=true,inclnolocationclasses=false,dumponexit=true,output=file,jmx=false -Xms256m -Xmx2g -Dfile.encoding=UTF-8 -Duser.country=AU -Duser.language=en -Duser.variant -ea -cp /Users/hoaphan/.gradle/caches/4.8.1/workerMain/gradle-worker.jar worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Test Executor 117'
Successfully started process 'Gradle Test Executor 117'

com.netflix.conductor.dao.mysql.MySQLQueueDAOTest > pollDeferredMessagesTest STANDARD_OUT
    00:21:50.483 [Test worker] INFO  com.netflix.conductor.dao.mysql.EmbeddedDatabase - Starting embedded database
    00:21:50.520 [Test worker] INFO  ch.vorburger.mariadb4j.Util - Created directory: /var/folders/hq/xc823d1x0y157v7k_swfl7wc0000gn/T/MariaDB4j/data/33307

com.netflix.conductor.dao.mysql.MySQLQueueDAOTest > pollDeferredMessagesTest FAILED
    java.lang.ExceptionInInitializerError
        at com.netflix.conductor.dao.mysql.MySQLDAOTestUtil.<init>(MySQLDAOTestUtil.java:34)
        at com.netflix.conductor.dao.mysql.MySQLQueueDAOTest.setup(MySQLQueueDAOTest.java:43)

        Caused by:
        java.lang.RuntimeException: Error unpacking embedded DB
            at ch.vorburger.mariadb4j.DB.unpackEmbeddedDb(DB.java:355)
            at ch.vorburger.mariadb4j.DB.newEmbeddedDB(DB.java:80)
            at com.netflix.conductor.dao.mysql.EmbeddedDatabase.startEmbeddedDatabase(EmbeddedDatabase.java:26)
            at com.netflix.conductor.dao.mysql.EmbeddedDatabase.<init>(EmbeddedDatabase.java:37)
            at com.netflix.conductor.dao.mysql.EmbeddedDatabase.<clinit>(EmbeddedDatabase.java:13)
            ... 2 more

            Caused by:
            java.io.IOException: Nothing found at classpath*:ch/vorburger/mariadb4j/mariadb-10.2.11/osx/**
                at ch.vorburger.mariadb4j.Util.extractFromClasspathToFile(Util.java:121)
                at ch.vorburger.mariadb4j.DB.unpackEmbeddedDb(DB.java:345)
                ... 6 more

    java.lang.NullPointerException
        at com.netflix.conductor.dao.mysql.MySQLQueueDAOTest.teardown(MySQLQueueDAOTest.java:49)
```

**Comment by vorburger** [comment]
>     java.io.IOException: Nothing found at classpath*:ch/vorburger/mariadb4j/mariadb-10.2.11/osx/**

so this would just mean that, for some reason (specific to your project, not this MariaDB4j library itself), you are missing this https://search.maven.org/artifact/ch.vorburger.mariaDB4j/mariaDB4j-db-mac64/10.2.11/jar artifact on your classpath...

Hoping this helped you; closing this issue, feel free to comment if not clear.
