### ISSUE TITLE
Exception if there are spaces in the data directory path

### ISSUE THREAD

**Issue by jahewson** [vorburger/MariaDB4j#30]
When using setDataDir() if the path contains spaces then newEmbeddedDB throws an exception. Looks like command line arguments are not being escaped. This could be an attack vector for a malicious user who has control over the database file name.

```
Exception in thread "main" ch.vorburger.exec.ManagedProcessException: An error occurred while installing the database
	at ch.vorburger.mariadb4j.DB.install(DB.java:117)
	at ch.vorburger.mariadb4j.DB.newEmbeddedDB(DB.java:68)
	...
Caused by: ch.vorburger.exec.ManagedProcessException: Program [/var/folders/m7/vwmfxlgd5655j5ysw0qbtyg00000gn/T/MariaDB4j/base/bin/mysql_install_db, "--datadir=/Users/john/my database", --basedir=/private/var/folders/m7/vwmfxlgd5655j5ysw0qbtyg00000gn/T/MariaDB4j/base, --no-defaults, --force, --skip-name-resolve] (in working directory /var/folders/m7/vwmfxlgd5655j5ysw0qbtyg00000gn/T/MariaDB4j/base) failed, exitValue=1, last 100 lines of console:
Installing MariaDB/MySQL system tables in './data' ...
/private/var/folders/m7/vwmfxlgd5655j5ysw0qbtyg00000gn/T/MariaDB4j/base/bin/mysqld: Too many arguments (first extra is '"--datadir=/Users/john/my').
150831 16:41:53 [ERROR] Aborting
```

**Comment by vorburger** [comment]
Hello @jahewson, thanks for your interest in MariaDB4j! That's a great point, and should be fixed ASAP.. I don't suppose you have the time and interest to join this project via a pull request that addresses this?

**Comment by vorburger** [comment]
https://issues.apache.org/jira/browse/EXEC-93

**Comment by vorburger** [comment]
@jahewson This particular problem re. space in setDataDir() is now fixed. Because of your comment “This could be an attack vector for a malicious user who has control over the database file name.” I’ve gone beyond a trivial quick fix, and done some work for a lower level and more generic - all arguments should now be escaped for spaces correctly. (If you find anything else, about this or other feedback on MariaDB4j, please do open new issues. Also any PRs always welcome.)

**Comment by jahewson** [comment]
:+1:
