### ISSUE TITLE
StartSimulatedForAllPlatformsTest failure due to java.io.FileNotFoundException: /tmp/MariaDB4j/base/bin/mysqld (Text file busy) 

### ISSUE THREAD

**Issue by vorburger** [vorburger/MariaDB4j#455]
`mvn test` fails for me locally due to the `StartSimulatedForAllPlatformsTest` failing like this:

```
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.113 sec <<< FAILURE!                                                
simulatedStartOSX(ch.vorburger.mariadb4j.StartSimulatedForAllPlatformsTest)  Time elapsed: 2.851 sec  <<< ERROR!                      
java.lang.RuntimeException: Error unpacking embedded DB                                                                               
        at ch.vorburger.mariadb4j.DB.unpackEmbeddedDb(DB.java:423)                                                                    
        at ch.vorburger.mariadb4j.StartSimulatedForAllPlatformsTest.checkPlatformStart(StartSimulatedForAllPlatformsTest.java:62)     
        at ch.vorburger.mariadb4j.StartSimulatedForAllPlatformsTest.simulatedStartOSX(StartSimulatedForAllPlatformsTest.java:52)      
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                             
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                           
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                   
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)                                                                 
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)                                       
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)                                        
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)                                         
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)                                          
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)                                                           
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)                                       
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)                                                              
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)                                         
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)                                          
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)                                                                
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)                                                            
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)                                                          
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.io.FileNotFoundException: /tmp/MariaDB4j/base/bin/mysqld (Text file busy)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
        at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:2440)
        at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:2397)
        at org.apache.commons.io.FileUtils.copyToFile(FileUtils.java:1085)
        at org.apache.commons.io.FileUtils.copyInputStreamToFile(FileUtils.java:992)
        at org.apache.commons.io.FileUtils.copyURLToFile(FileUtils.java:1112)
        at ch.vorburger.mariadb4j.Util$1.apply(Util.java:138)
        at ch.vorburger.mariadb4j.Util.tryN(Util.java:159)
        at ch.vorburger.mariadb4j.Util.extractFromClasspathToFile(Util.java:134)
        at ch.vorburger.mariadb4j.DB.unpackEmbeddedDb(DB.java:413)
        ... 34 more
```

This is NOT a #452 kind of issue; the `Text file busy` means that `FileUtils` can't write to `mysqld`... I suspect what's happening here is hat my new computer is too fast 😈 and the FS is still busy deleting the file from the previous test run. Looks like  `FileUtils.deleteDirectory()` is somehow... asynchronous?

This blocks #334. Does anyone reading this using and interested in helping this project want to look into fixing this.

**Comment by vorburger** [comment]
For the record, interestingly, when I launch just `StartSimulatedForAllPlatformsTest` in an IDE, then it passes.
