### ISSUE TITLE
An error occurred while running a script file sourced from the classpath at: schema.sql

### ISSUE THREAD

**Issue by holmofy** [vorburger/MariaDB4j#458]
```sh
Caused by: ch.vorburger.exec.ManagedProcessException: An error occurred while running a script file sourced from the classpath at: schema.sql
	at ch.vorburger.mariadb4j.DB.run(DB.java:300)
	at ch.vorburger.mariadb4j.DB.source(DB.java:260)
	at ch.vorburger.mariadb4j.DB.source(DB.java:239)
	at com.doutiaotech.apollo.infrastructure.mysql.BaseDaoTest$TestDbConfig.init(BaseDaoTest.java:60)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
	... 44 more
Caused by: ch.vorburger.exec.ManagedProcessException: Program [D:\apollo\infrastructure-mysql\target\test-mysql\base\bin\mysql.exe, --port=33306] (in working directory D:\apollo\infrastructure-mysql\target\test-mysql\base) failed, exitValue=1, last 100 lines of console:
ERROR 2013 (HY000) at line 3: Lost connection to MySQL server during query
	at ch.vorburger.exec.ManagedProcess.checkResult(ManagedProcess.java:312)
	at ch.vorburger.exec.ManagedProcess.waitForExitMaxMsWithoutLog(ManagedProcess.java:450)
	at ch.vorburger.exec.ManagedProcess.waitForExit(ManagedProcess.java:418)
	at ch.vorburger.mariadb4j.DB.run(DB.java:298)
	... 54 more
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:48)
	at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:200)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

mysql schema.sql:
```sql
create database if not exists apollo character set = utf8mb4;

grant all on apollo.* to apollo;

use apollo;

create table if not exists `user`
(
    id            bigint primary key auto_increment,
    shop_name     varchar(128) not null,
    created       datetime     not null,
    last_modified datetime     not null
);
```
My sql script can be run in docker

**Comment by vorburger** [comment]
You would need to provide more of the log to help us understand why `Process exited with an error: 1`.

**Comment by vorburger** [comment]
@holmofy please comment here if you have the full log and we can re-open this issue if needed.
