### ISSUE TITLE
NoClassDefFoundError in shutdown hook thread

### ISSUE THREAD

**Issue by paulroemer** [vorburger/MariaDB4j#57]
Hey guys, 

first of all thanks for this awesome piece of software. It helps us a lot in our current project.

There is only one problem:

```
Shutdown Hook Deletion Thread for Temporary DB ../tmp/devdb 2017-01-04 19:49:42 INFO [c.v.m.DB] - cleanupOnExit() ShutdownHook now stopping database
Exec Default Executor 2017-01-04 19:49:44 INFO [c.v.e.ManagedProcess] - Program [/tmp/MariaDB4j/base/bin/mysqld, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M, --basedir=/tmp/MariaDB4j/base, --datadir=/home/vaadin/repos/tmp/devdb, --port=4223, --socket=/tmp/MariaDB4j.4223.sock] (in working directory /tmp/MariaDB4j/base) just exited, with value 0
Shutdown Hook Deletion Thread for Temporary DB ../tmp/devdb 2017-01-04 19:49:44 INFO [c.v.e.ManagedProcess] - Successfully destroyed Program [/tmp/MariaDB4j/base/bin/mysqld, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M, --basedir=/tmp/MariaDB4j/base, --datadir=/home/vaadin/repos/tmp/devdb, --port=4223, --socket=/tmp/MariaDB4j.4223.sock] (in working directory /tmp/MariaDB4j/base)
Shutdown Hook Deletion Thread for Temporary DB ../tmp/devdb 2017-01-04 19:49:44 INFO [c.v.m.DB] - Database stopped.
Shutdown Hook Deletion Thread for Temporary DB ../tmp/devdb 2017-01-04 19:49:44 INFO [c.v.m.DB] - cleanupOnExit() ShutdownHook quietly deleting temporary DB base directory: /tmp/MariaDB4j/base
Exception in thread "Shutdown Hook Deletion Thread for Temporary DB ../tmp/devdb" java.lang.NoClassDefFoundError: org/apache/commons/io/FilenameUtils
        at org.apache.commons.io.FileUtils.isSymlink(FileUtils.java:2924)
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1534)
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270)
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653)
        at org.apache.commons.io.FileUtils.deleteQuietly(FileUtils.java:1566)
        at ch.vorburger.mariadb4j.DB$1.run(DB.java:373)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.FilenameUtils
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
        at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:560)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 6 more
```

That happens if we start our web application via the maven jetty plugin and stop it via Ctrl-C.

It does not hurt us much but it's annoying. I already tried to set the stopWait in the plugin's configuration but that did not help.

Has someone else the same problem?

Cheers,
  Paul

**Comment by vorburger** [comment]
@paulroemer thanks for your interest in MariaDB4j and support to other users by contributing with comments on the issues list! I just had a quick closer look at this one .. so it seems that mariadb4j.DB calls commons.io.FileUtils.deleteQuietly which in turn ends up calling (still commons-io's) FilenameUtils.isSystemWindows, that's line 2924, but ClassNotFoundException for FilenameUtils. 

Assuming that this may be some JAR version hell kind of issues, I've verified that FilenameUtils is Commons IO 2.4 and still in the latest 2.5, so not like maybe deprecated and removed, so that's not it.

The only possible explanation I can think of then, as this generally works otherwise, is perhaps that the (parent) classpath of the maven jetty plugin of your project where you're hitting this has e.g a FAT JAR (not shaded) that includes Commons IO but misses FilenameUtils .. a bit vague, I know, but it must be some weird issue like that. 

Or maybe that (jetty) Maven plugin copies the WAR's JARs somewhere, like a temp WEB-INF/lib (I've no idea how that works), and delete that BEFORE that JVM shutdown hook that MariaDB4j installs gets a chance to run? Just a guess.

**Comment by paulroemer** [comment]
Yes, it's very likely some pretty weird issue. Honestly, I hoped it's already known and easy to fix.

Problem is that I cannot fix it now as it's not worth the effort.

Should we keep it open for others anyway?
