### ISSUE TITLE
Source doesn't select database from seed

### ISSUE THREAD

**Issue by StruckCroissant** [vorburger/MariaDB4j#596]
I've been trying to use MariaDB4j as a datasource for integration testing - but I can't get it to properly load the SQL seed file.

## Here is stack trace I'm getting:
```
Caused by: ch.vorburger.exec.ManagedProcessException: An error occurred while running a script file sourced from the classpath at: db.init/gamedb_seed.sql
	at ch.vorburger.mariadb4j.DB.run(DB.java:371)
	at ch.vorburger.mariadb4j.DB.source(DB.java:306)
	at ch.vorburger.mariadb4j.DB.source(DB.java:287)
	at ch.vorburger.mariadb4j.DB.source(DB.java:256)
	at com.StruckCroissant.GameDB.testDbConfig.dataSource(testDbConfig.java:37)
	at com.StruckCroissant.GameDB.testDbConfig$$EnhancerBySpringCGLIB$$177667b6.CGLIB$dataSource$2(<generated>)
	at com.StruckCroissant.GameDB.testDbConfig$$EnhancerBySpringCGLIB$$177667b6$$FastClassBySpringCGLIB$$27daa94c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at com.StruckCroissant.GameDB.testDbConfig$$EnhancerBySpringCGLIB$$177667b6.dataSource(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 146 more
Caused by: ch.vorburger.exec.ManagedProcessException: Program [C:\Users\dakot\AppData\Local\Temp\MariaDB4j\base\bin\mysql.exe, -Dgamedb, --port=15075] (in working directory C:\Users\dakot\AppData\Local\Temp\MariaDB4j\base) failed, exitValue=1, last 100 lines of console:
ERROR 1049 (42000): Unknown database 'gamedb'
	at ch.vorburger.exec.ManagedProcess.checkResult(ManagedProcess.java:310)
	at ch.vorburger.exec.ManagedProcess.startExecute(ManagedProcess.java:216)
	at ch.vorburger.exec.ManagedProcess.start(ManagedProcess.java:155)
	at ch.vorburger.mariadb4j.DB.run(DB.java:368)
	... 160 more
```

## Db config class:
```java
@Configuration
@EnableAutoConfiguration(exclude = {DataSourceAutoConfiguration.class})
@PropertySource("classpath:application-test.yaml")
@ActiveProfiles("test")
public class testDbConfig {

  @Bean(name = "testDbService")
  public MariaDB4jSpringService mariaDB4jSpringService() {
    return new MariaDB4jSpringService();
  }

  @Bean
  public DataSource dataSource(
      @Qualifier("testDbService") MariaDB4jSpringService mariaDB4jSpringService,
      @Value("${app.datasource.name}") String databaseName,
      @Value("${app.datasource.username}") String datasourcePassword,
      @Value("${app.datasource.driver-class-name}") String datasourceDriver
  ) throws ManagedProcessException {
    mariaDB4jSpringService
        .getDB()
        .source("db.init/gamedb_seed.sql", databaseName);


    DBConfigurationBuilder dbConfigurationBuilder = mariaDB4jSpringService.getConfiguration();

    return DataSourceBuilder.create()
        .driverClassName(datasourceDriver)
        .url(dbConfigurationBuilder.getURL(databaseName))
        .username(datasourcePassword)
        .password(datasourcePassword)
        .build();
  }

  @Bean
  public JdbcTemplate jdbcTemplate(DataSource dataSource) {
    return new JdbcTemplate(dataSource);
  }
}
```

## config properties:
```yaml
app:
  datasource:
    jdbc-url: "jdbc:mariadb://localhost:3307/gamedb"
    username: root
    password:
    name: gamedb
    driver-class-name: "org.mariadb.jdbc.Driver"
server:
  error:
    include-details: always
    include-message: always
  port: 9191
spring: # TODO Combine spring & app settings?
  flyway:
    enabled: false
    validate-on-migrate: true
    user: root
    password:
    url: "jdbc:mariadb://localhost:3307/gamedb"
    baseline-on-migrate: true
```

The database name is consistent through all the configuration & database itself. The first line of the sql seed file lists database name as `gamedb`. Not sure if this is an issue with my setup or the way I'm using the `source` function - at first I thought the `db_name` field selected the database name from the seed file - but now I'm not sure if it does that or overwrites the database name with a new one. I highly suspect its the latter.

Anyways, thanks for the assistance in advance! Great library - i'm pretty sure i'm just setting it up wrong.

**Comment by StruckCroissant** [comment]
### Nevermind I fixed it 🥳 

Issue was due to not using `createDB(databaseName)` before using the `source` function. Turns out `source` uses a Database name that's already tied to load the seed file into. I feel like this could possibly use some extra documentation as I had some trouble actually finding details about this.

## New configuration class:
```java
@Bean
  public DataSource dataSource(
      @Qualifier("testDbService") MariaDB4jSpringService mariaDB4jSpringService,
      @Value("${app.datasource.name}") String databaseName,
      @Value("${app.datasource.username}") String datasourcePassword,
      @Value("${app.datasource.driver-class-name}") String datasourceDriver
  ) throws ManagedProcessException {
    //Added createDB before source
    mariaDB4jSpringService.getDB().createDB(databaseName);
    mariaDB4jSpringService.getDB().source("db.init/gamedb_seed.sql", databaseName);


    DBConfigurationBuilder dbConfigurationBuilder = mariaDB4jSpringService.getConfiguration();

    return DataSourceBuilder.create()
        .driverClassName(datasourceDriver)
        .url(dbConfigurationBuilder.getURL(databaseName))
        .username(datasourcePassword)
        .password(datasourcePassword)
        .build();
  }
```

**Comment by vorburger** [comment]
> Nevermind I fixed it 🥳

@StruckCroissant great, happy for you!

> I feel like this could possibly use some extra documentation as I had some trouble actually finding details about this.

Feel free to open a Pull Request added JavaDoc or README MD documentation about this where you would have wanted to look for it.
