### ISSUE TITLE
NullPointerException using MariaDb4J with main HikariDatasource

### ISSUE THREAD

**Issue by StruckCroissant** [vorburger/MariaDB4j#597]
I'm trying to set up an embedded MariaDb4J datasource for my Integration tests alongside a HikariDatasource/Docker Database that I use for my main Spring Boot application.

So far I can run the unit tests & have the tests run against the embedded MariaDb4J test DB properly, but I cannot run the main application and have it properly run against the HikariDatabase configured by my `application.yaml` file. 

### The stack trace that I get when I run my main app:
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [ch/vorburger/mariadb4j/springboot/autoconfigure/DataSourceAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.19.jar:5.3.19]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.19.jar:5.3.19]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.7.jar:2.6.7]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740) ~[spring-boot-2.6.7.jar:2.6.7]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415) ~[spring-boot-2.6.7.jar:2.6.7]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[spring-boot-2.6.7.jar:2.6.7]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312) ~[spring-boot-2.6.7.jar:2.6.7]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[spring-boot-2.6.7.jar:2.6.7]
	at com.StruckCroissant.GameDB.GameDbApplication.main(GameDbApplication.java:18) ~[classes/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.19.jar:5.3.19]
	... 19 common frames omitted
Caused by: java.lang.NullPointerException: null
	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[na:na]
	at java.base/java.util.concurrent.ConcurrentHashMap.putIfAbsent(ConcurrentHashMap.java:1541) ~[na:na]
	at java.base/java.lang.ClassLoader.getClassLoadingLock(ClassLoader.java:666) ~[na:na]
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:651) ~[na:na]
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	at com.zaxxer.hikari.HikariConfig.attemptFromContextLoader(HikariConfig.java:970) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.HikariConfig.setDriverClassName(HikariConfig.java:480) ~[HikariCP-4.0.3.jar:na]
	at org.springframework.boot.jdbc.DataSourceBuilder$MappedDataSourceProperty.set(DataSourceBuilder.java:460) ~[spring-boot-2.6.7.jar:2.6.7]
	at org.springframework.boot.jdbc.DataSourceBuilder$MappedDataSourceProperties.set(DataSourceBuilder.java:355) ~[spring-boot-2.6.7.jar:2.6.7]
	at org.springframework.boot.jdbc.DataSourceBuilder.build(DataSourceBuilder.java:190) ~[spring-boot-2.6.7.jar:2.6.7]
	at ch.vorburger.mariadb4j.springboot.autoconfigure.DataSourceAutoConfiguration.dataSource(DataSourceAutoConfiguration.java:43) ~[mariaDB4j-springboot-2.5.3.jar:na]
	at ch.vorburger.mariadb4j.springboot.autoconfigure.DataSourceAutoConfiguration$$EnhancerBySpringCGLIB$$aa0eca5e.CGLIB$dataSource$0(<generated>) ~[mariaDB4j-springboot-2.5.3.jar:na]
	at ch.vorburger.mariadb4j.springboot.autoconfigure.DataSourceAutoConfiguration$$EnhancerBySpringCGLIB$$aa0eca5e$$FastClassBySpringCGLIB$$2eb160d3.invoke(<generated>) ~[mariaDB4j-springboot-2.5.3.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.19.jar:5.3.19]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.19.jar:5.3.19]
	at ch.vorburger.mariadb4j.springboot.autoconfigure.DataSourceAutoConfiguration$$EnhancerBySpringCGLIB$$aa0eca5e.dataSource(<generated>) ~[mariaDB4j-springboot-2.5.3.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.19.jar:5.3.19]
	... 20 common frames omitted
```

If I add `exclude = {DatabaseAutoConfiguration.class}` to the `@SpringBootApplication` annotation on my main class this issue seems to go away - except it is no longer pulling from the Docker DB, but instead the embedded database.

# Here's the rest of the revelant code:

### Integration Test Config:
```Java
@Configuration
@PropertySource("classpath:test.properties")
public class testDbConfig {

  @Bean(name = "testDbService")
  public MariaDB4jSpringService mariaDB4jSpringService() {
    return new MariaDB4jSpringService();
  }

  @Bean(name = "testDbDatasource")
  public DataSource dataSource(
      @Qualifier("testDbService") MariaDB4jSpringService mariaDB4jSpringService,
      @Value("${app.datasource.name}") String databaseName,
      @Value("${app.datasource.username}") String datasourcePassword,
      @Value("${app.datasource.driver-class-name}") String datasourceDriver
  ) throws ManagedProcessException {
    mariaDB4jSpringService.getDB().createDB(databaseName);
    mariaDB4jSpringService.getDB().source("db/init/gamedb_seed.sql", databaseName);


    DBConfigurationBuilder dbConfigurationBuilder = mariaDB4jSpringService.getConfiguration();

    return DataSourceBuilder.create()
        .driverClassName(datasourceDriver)
        .url(dbConfigurationBuilder.getURL(databaseName))
        .username(datasourcePassword)
        .password(datasourcePassword)
        .build();
  }

  @Bean(name = "testDbJdbcTemplate")
  public JdbcTemplate jdbcTemplate(@Qualifier("testDbDatasource") DataSource dataSource) {
    return new JdbcTemplate(dataSource);
  }
}
```

## test.properties
```
app.datasource.jdbc-url="jdbc:mariadb://localhost:3307/gamedb"
app.datasource.username= root
app.datasource.password=
app.datasource.name=gamedb
app.datasource.driver-class-name=org.mariadb.jdbc.Driver
```

## Main datasource
```
@Configuration
public class MysqlDatasource {

  /**
   * Creates a hikari datasource configured via properties in application.yaml
   *
   * @return HikariDataSource
   * @see ../application.yaml
   */
  @Bean
  @Primary
  @ConfigurationProperties("app.datasource")
  public HikariDataSource hikariDataSource() {
    return DataSourceBuilder.create().type(HikariDataSource.class).build();
  }
}
```

## application.yaml
```
app:
  datasource:
    jdbc-url: "jdbc:mariadb://localhost:3306/gamedb_db"
    username: root
    password: mariadb
server:
  error:
    include-details: always
    include-message: always
  port: 9191
spring: # TODO Combine spring & app settings
  flyway:
    enabled: true
    validate-on-migrate: true
    user: root
    password: mariadb
    url: "jdbc:mariadb://localhost:3306/gamedb_db"
    baseline-on-migrate: true
```

I'm not sure what's going on here. I'm fairly certain I have the beans & application context wired up correctly, although the issue itself seems to be with MariaDb4J trying to take priority over the Datasource that I already have. I'm not even sure why the test beans are initializing like this even though I'm executing the main application.

**Comment by StruckCroissant** [comment]
Just did some testing & it seems like the issue might be with the `mariaDB4j-springboot` dependency. On init it seems to conflict with the HikariDatasource that I've already configured. The issue doesn't go away until I delete the dependency entirely - maybe I can write something into `pom.xml` that disables the db init when the 'test' profile is active?

**Comment by StruckCroissant** [comment]
Switched to `MariaDb4J` in my pom instead of `MariaDb4J-Spring` & that fixed the issue. I'm going to close this - but this is something I'm most likely going to make a documentation PR for in the future.
