### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by mntwinsfan** [vorburger/MariaDB4j#68]
I have been successfully using MariaDB4j until today.  All of a sudden I am getting the following error:

`"ERROR 1045 (28000): Access denied for user 'Grant'@'localhost' (using password: NO)"`

And this exception a few lines below:

`nested exception is ch.vorburger.exec.ManagedProcessException: An error occurred while running a command: create database if not exists 'test'
`

I'm calling the database as a Spring bean as follows:

```
	@Bean
	public void testDatabase()throws ManagedProcessException{
		// Start database
		DBConfigurationBuilder configBuilder = DBConfigurationBuilder.newBuilder();
		configBuilder.setPort( 3310 );
		configBuilder.setDataDir("/work/db");
		db = DB.newEmbeddedDB( configBuilder.build() );
		db.start();
		db.createDB( "test" );
	}
```

I have deleted the database files (/work/db) in case there was corruption but didn't help.  I am running this on a Windows machine.

Has anyone seen this before and know what to do to correct?

**Comment by vorburger** [comment]
@mntwinsfan your log should show the STDOUT of the mysql process and there is probably some more uesful details in there which will let you understand why An error occurred while running a command: create database if not exists 'test' ...

**Comment by mntwinsfan** [comment]
Here is STDOUT:

2017-04-24 10:19:55.821 INFO  Util - Created directory: C:\Users\Default\AppData\Local\Temp\MariaDB4j\base
2017-04-24 10:19:55.847 INFO  Util - Created directory: C:\Users\Default\AppData\Local\Temp\MariaDB4j\base\libs
2017-04-24 10:20:15.676 INFO  Util - Unpacked 41 files from classpath*:ch/vorburger/mariadb4j/mariadb-10.1.20/win32/** to C:\Users\Default\AppData\Local\Temp\MariaDB4j\base
2017-04-24 10:20:15.676 INFO  DB - Installing a new embedded database to: C:\Users\Default\AppData\Local\Temp\MariaDB4j\base
2017-04-24 10:20:15.694 INFO  ManagedProcess - Starting Program [C:\Users\Default\AppData\Local\Temp\MariaDB4j\base\bin\mysql_install_db.exe, --datadir=C:\Work\hub\db] (in working directory C:\Users\Default\AppData\Local\Temp\MariaDB4j\base)
2017-04-24 10:20:15.810 INFO  ManagedProcess - Thread is now going to wait for this process to terminate itself: Program [C:\Users\Default\AppData\Local\Temp\MariaDB4j\base\bin\mysql_install_db.exe, --datadir=C:\Work\hub\db] (in working directory C:\Users\Default\AppData\Local\Temp\MariaDB4j\base)
2017-04-24 10:20:15.957 INFO  ManagedProcess - mysql_install_db.exe: Running bootstrap
2017-04-24 10:20:16.618 INFO  ManagedProcess - mysql_install_db.exe: 2017-04-24 10:20:16 47512 [Note] C:\Users\Default\AppData\Local\Temp\MariaDB4j\base\bin\mysqld.exe (mysqld 10.1.20-MariaDB) starting as process 51572 ...
2017-04-24 10:20:18.969 INFO  ManagedProcess - mysql_install_db.exe: Removing default user
2017-04-24 10:20:23.140 INFO  ManagedProcess - mysql_install_db.exe: Creating my.ini file
2017-04-24 10:20:23.144 INFO  ManagedProcess - mysql_install_db.exe: Creation of the database was successfull
2017-04-24 10:20:23.145 INFO  ManagedProcess - Program [C:\Users\Default\AppData\Local\Temp\MariaDB4j\base\bin\mysql_install_db.exe, --datadir=C:\Work\hub\db] (in working directory C:\Users\Default\AppData\Local\Temp\MariaDB4j\base) just exited, with value 0
2017-04-24 10:20:23.189 INFO  DB - Installation complete.
2017-04-24 10:20:23.189 INFO  DB - Starting up the database...
2017-04-24 10:20:23.190 INFO  DB - mysqld executable: C:\Users\Default\AppData\Local\Temp\MariaDB4j\base\bin\mysqld.exe
2017-04-24 10:20:23.191 INFO  ManagedProcess - Starting Program [C:\Users\Default\AppData\Local\Temp\MariaDB4j\base\bin\mysqld.exe, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M, --basedir=C:\Users\Default\AppData\Local\Temp\MariaDB4j\base, --datadir=C:\Work\hub\db, --port=3310] (in working directory C:\Users\Default\AppData\Local\Temp\MariaDB4j\base)
2017-04-24 10:20:23.191 INFO  ManagedProcess - Thread will wait for "mysqld.exe: ready for connections." to appear in Console output of process Program [C:\Users\Default\AppData\Local\Temp\MariaDB4j\base\bin\mysqld.exe, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M, --basedir=C:\Users\Default\AppData\Local\Temp\MariaDB4j\base, --datadir=C:\Work\hub\db, --port=3310] (in working directory C:\Users\Default\AppData\Local\Temp\MariaDB4j\base) for max. 30000ms
2017-04-24 10:20:23.243 INFO  ManagedProcess - mysqld.exe: 2017-04-24 10:20:23 36736 [Note] C:\Users\Default\AppData\Local\Temp\MariaDB4j\base\bin\mysqld.exe (mysqld 10.1.20-MariaDB) starting as process 54304 ...
2017-04-24 10:20:23.270 INFO  ManagedProcess - mysqld.exe: 2017-04-24 10:20:23 36736 [Note] InnoDB: Using mutexes to ref count buffer pool pages
2017-04-24 10:20:23.271 INFO  ManagedProcess - mysqld.exe: 2017-04-24 10:20:23 36736 [Note] InnoDB: The InnoDB memory heap is disabled
2017-04-24 10:20:23.271 INFO  ManagedProcess - mysqld.exe: 2017-04-24 10:20:23 36736 [Note] InnoDB: Mutexes and rw_locks use Windows interlocked functions
2017-04-24 10:20:23.272 INFO  ManagedProcess - mysqld.exe: 2017-04-24 10:20:23 36736 [Note] InnoDB: _mm_lfence() and _mm_sfence() are used for memory barrier
2017-04-24 10:20:23.272 INFO  ManagedProcess - mysqld.exe: 2017-04-24 10:20:23 36736 [Note] InnoDB: Compressed tables use zlib 1.2.3
2017-04-24 10:20:23.273 INFO  ManagedProcess - mysqld.exe: 2017-04-24 10:20:23 36736 [Note] InnoDB: Using generic crc32 instructions
2017-04-24 10:20:23.275 INFO  ManagedProcess - mysqld.exe: 2017-04-24 10:20:23 36736 [Note] InnoDB: Initializing buffer pool, size = 128.0M
2017-04-24 10:20:23.280 INFO  ManagedProcess - mysqld.exe: 2017-04-24 10:20:23 36736 [Note] InnoDB: Completed initialization of buffer pool
2017-04-24 10:20:23.437 INFO  ManagedProcess - mysqld.exe: 2017-04-24 10:20:23 36736 [Note] InnoDB: Setting log file .\ib_logfile101 size to 48 MB
2017-04-24 10:20:25.301 INFO  ManagedProcess - mysqld.exe: 2017-04-24 10:20:25 36736 [Note] InnoDB: Setting log file .\ib_logfile1 size to 48 MB
2017-04-24 10:20:26.559 INFO  ManagedProcess - mysqld.exe: 2017-04-24 10:20:26 36736 [Note] InnoDB: Renaming log file .\ib_logfile101 to .\ib_logfile0
2017-04-24 10:20:26.561 INFO  ManagedProcess - mysqld.exe: 2017-04-24 10:20:26 36736 [Warning] InnoDB: New log files created, LSN=1623584
2017-04-24 10:20:26.564 INFO  ManagedProcess - mysqld.exe: 2017-04-24 10:20:26 36736 [Note] InnoDB: Highest supported file format is Barracuda.
2017-04-24 10:20:26.859 INFO  ManagedProcess - mysqld.exe: 2017-04-24 10:20:26 36736 [Note] InnoDB: 128 rollback segment(s) are active.
2017-04-24 10:20:26.860 INFO  ManagedProcess - mysqld.exe: 2017-04-24 10:20:26 36736 [Note] InnoDB: Waiting for purge to start
2017-04-24 10:20:26.919 INFO  ManagedProcess - mysqld.exe: 2017-04-24 10:20:26 36736 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.34-79.1 started; log sequence number 1624076
2017-04-24 10:20:27.145 INFO  ManagedProcess - mysqld.exe: 2017-04-24 10:20:27 53964 [Note] InnoDB: Dumping buffer pool(s) not yet started
2017-04-24 10:20:27.152 INFO  ManagedProcess - mysqld.exe: 2017-04-24 10:20:27 36736 [Note] Plugin 'FEEDBACK' is disabled.
2017-04-24 10:20:27.198 INFO  ManagedProcess - mysqld.exe: 2017-04-24 10:20:27 36736 [Note] Server socket created on IP: '::'.
2017-04-24 10:20:27.327 INFO  ManagedProcess - mysqld.exe: 2017-04-24 10:20:27 36736 [Note] C:\Users\Default\AppData\Local\Temp\MariaDB4j\base\bin\mysqld.exe: ready for connections.
2017-04-24 10:20:27.327 INFO  ManagedProcess - mysqld.exe: Version: '10.1.20-MariaDB'  socket: ''  port: 3310  mariadb.org binary distribution
2017-04-24 10:20:27.366 INFO  DB - Database startup complete.
2017-04-24 10:20:27.367 INFO  DB - Running a command: create database if not exists `test`;
2017-04-24 10:20:27.367 INFO  ManagedProcess - Starting Program [C:\Users\Default\AppData\Local\Temp\MariaDB4j\base\bin\mysql.exe, --port=3310] (in working directory C:\Users\Default\AppData\Local\Temp\MariaDB4j\base)
2017-04-24 10:20:27.471 INFO  ManagedProcess - Thread is now going to wait for this process to terminate itself: Program [C:\Users\Default\AppData\Local\Temp\MariaDB4j\base\bin\mysql.exe, --port=3310] (in working directory C:\Users\Default\AppData\Local\Temp\MariaDB4j\base)
2017-04-24 10:20:47.641 ERROR ManagedProcess - mysql.exe: ERROR 2013 (HY000): Lost connection to MySQL server at 'waiting for initial communication packet', system error: 0 "Internal error/check (Not system error)"
2017-04-24 10:20:47.649 ERROR ManagedProcess - Program [C:\Users\Default\AppData\Local\Temp\MariaDB4j\base\bin\mysql.exe, --port=3310] (in working directory C:\Users\Default\AppData\Local\Temp\MariaDB4j\base) failed unexpectedly
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404) ~[commons-exec-1.3.jar:1.3]
	at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:48) ~[commons-exec-1.3.jar:1.3]
	at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:200) ~[commons-exec-1.3.jar:1.3]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
2017-04-24 10:20:47.688 ERROR ManagedProcess - Program [C:\Users\Default\AppData\Local\Temp\MariaDB4j\base\bin\mysql.exe, --port=3310] (in working directory C:\Users\Default\AppData\Local\Temp\MariaDB4j\base) failed
2017-04-24 10:20:47.690 WARN  GenericWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'transactionManager': Unsatisfied dependency expressed through field 'dataSource': Error creating bean with name 'testDatabase' defined in myproject..TestConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [myproject..TestDatabase]: Factory method 'testDatabase' threw exception; nested exception is ch.vorburger.exec.ManagedProcessException: An error occurred while running a command: create database if not exists `test`;; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'testDatabase' defined in myproject..TestConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [myproject..TestDatabase]: Factory method 'testDatabase' threw exception; nested exception is ch.vorburger.exec.ManagedProcessException: An error occurred while running a command: create database if not exists `test`;
2017-04-24 10:20:47.695 ERROR TestContextManager - Caught exception while allowing TestExecutionListener [org.springframework.test.context.web.ServletTestExecutionListener@4baf352a] to prepare test instance [myproject..database.DatabaseManagerIT@1bb1fde8]
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124) ~[spring-test-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:83) ~[spring-test-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:189) ~[spring-test-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:131) ~[spring-test-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:230) ~[spring-test-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:228) [spring-test-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:287) [spring-test-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:289) [spring-test-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:247) [spring-test-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94) [spring-test-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61) [spring-test-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70) [spring-test-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191) [spring-test-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53) [surefire-junit4-2.10.jar:2.10]
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123) [surefire-junit4-2.10.jar:2.10]
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104) [surefire-junit4-2.10.jar:2.10]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40]
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164) [surefire-api-2.10.jar:2.10]
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110) [surefire-booter-2.10.jar:2.10]
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175) [surefire-booter-2.10.jar:2.10]
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107) [surefire-booter-2.10.jar:2.10]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68) [surefire-booter-2.10.jar:2.10]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'transactionManager': Unsatisfied dependency expressed through field 'dataSource': Error creating bean with name 'testDatabase' defined in myproject..TestConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [myproject..TestDatabase]: Factory method 'testDatabase' threw exception; nested exception is ch.vorburger.exec.ManagedProcessException: An error occurred while running a command: create database if not exists `test`;; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'testDatabase' defined in myproject..TestConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [myproject..TestDatabase]: Factory method 'testDatabase' threw exception; nested exception is ch.vorburger.exec.ManagedProcessException: An error occurred while running a command: create database if not exists `test`;
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:569) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:349) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:776) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861) ~[spring-context-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541) ~[spring-context-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.test.context.web.AbstractGenericWebContextLoader.loadContext(AbstractGenericWebContextLoader.java:134) ~[spring-test-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.test.context.web.AbstractGenericWebContextLoader.loadContext(AbstractGenericWebContextLoader.java:61) ~[spring-test-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.delegateLoading(AbstractDelegatingSmartContextLoader.java:108) ~[spring-test-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.loadContext(AbstractDelegatingSmartContextLoader.java:251) ~[spring-test-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:98) ~[spring-test-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:116) ~[spring-test-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	... 31 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'testDatabase' defined in myproject..TestConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [myproject..TestDatabase]: Factory method 'testDatabase' threw exception; nested exception is ch.vorburger.exec.ManagedProcessException: An error occurred while running a command: create database if not exists `test`;
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1123) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1018) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:296) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:207) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1214) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1054) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1019) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:566) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	... 49 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [myproject..TestDatabase]: Factory method 'testDatabase' threw exception; nested exception is ch.vorburger.exec.ManagedProcessException: An error occurred while running a command: create database if not exists `test`;
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	... 64 common frames omitted
Caused by: ch.vorburger.exec.ManagedProcessException: An error occurred while running a command: create database if not exists `test`;
	at ch.vorburger.mariadb4j.DB.run(DB.java:270) ~[mariaDB4j-core-2.2.3.jar:na]
	at ch.vorburger.mariadb4j.DB.run(DB.java:243) ~[mariaDB4j-core-2.2.3.jar:na]
	at ch.vorburger.mariadb4j.DB.run(DB.java:247) ~[mariaDB4j-core-2.2.3.jar:na]
	at ch.vorburger.mariadb4j.DB.createDB(DB.java:278) ~[mariaDB4j-core-2.2.3.jar:na]
	at myproject..TestDatabase.open(TestDatabase.java:22) ~[test-classes/:na]
	at myproject..TestConfig.testDatabase(TestConfig.java:22) ~[test-classes/:na]
	at myproject..TestConfig$$EnhancerBySpringCGLIB$$c7d1fa8a.CGLIB$testDatabase$0(<generated>) ~[test-classes/:na]
	at myproject..TestConfig$$EnhancerBySpringCGLIB$$c7d1fa8a$$FastClassBySpringCGLIB$$55018ea8.invoke(<generated>) ~[test-classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356) ~[spring-context-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at myproject..TestConfig$$EnhancerBySpringCGLIB$$c7d1fa8a.testDatabase(<generated>) ~[test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	... 65 common frames omitted
Caused by: ch.vorburger.exec.ManagedProcessException: Program [C:\Users\Default\AppData\Local\Temp\MariaDB4j\base\bin\mysql.exe, --port=3310] (in working directory C:\Users\Default\AppData\Local\Temp\MariaDB4j\base) failed, exitValue=1, last 100 lines of console:
ERROR 2013 (HY000): Lost connection to MySQL server at 'waiting for initial communication packet', system error: 0 "Internal error/check (Not system error)"
	at ch.vorburger.exec.ManagedProcess.checkResult(ManagedProcess.java:297) ~[mariaDB4j-core-2.2.3.jar:na]
	at ch.vorburger.exec.ManagedProcess.waitForExitMaxMsWithoutLog(ManagedProcess.java:415) ~[mariaDB4j-core-2.2.3.jar:na]
	at ch.vorburger.exec.ManagedProcess.waitForExit(ManagedProcess.java:385) ~[mariaDB4j-core-2.2.3.jar:na]
	at ch.vorburger.mariadb4j.DB.run(DB.java:268) ~[mariaDB4j-core-2.2.3.jar:na]
	... 80 common frames omitted
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404) ~[commons-exec-1.3.jar:1.3]
	at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:48) ~[commons-exec-1.3.jar:1.3]
	at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:200) ~[commons-exec-1.3.jar:1.3]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_40]

**Comment by vorburger** [comment]
right, so your mysql which is the native "client" application tells you that `ERROR 2013 (HY000): Lost connection to MySQL server at 'waiting for initial communication packet', system error: 0 "Internal error/check (Not system error)"` - it seems to fail to talk to your mysqld native "server" application over the local network port that these communicate with each other...

Both of these native applications are launched by MariaDB4j, the Java wrapper (this project), but as to why these two fail to communicate to each other on your system I'm afraid I have no idea... It works for a lot of other people and seems to have work for you until recently, perhaps something change on your system?

**Comment by mntwinsfan** [comment]
I found the problem.  I had forgotten I had setup a SSH tunnel listening on port 3310 which I had open last night.  hence Hence the access denied errors.  Then today the SSH session disconnected but putty was still open, hence the packet errors.  Guess this would be a good example of where I should have let MariaDB4j pick an open port automatically.  Thanks for your response.
