### ISSUE TITLE
How to run multiple tests within a Test Suite, each with own MariaDB4jSpringService?

### ISSUE THREAD

**Issue by sddakoty** [vorburger/MariaDB4j#95]
When I run the following tests individually, they both work.
But if I run both tests from within a `Testsuite`, then an exception is thrown that the port is already in use. But why? Probably the server is not shut down correctly if started within `@BeforeClass`?

Sidenote: I cannot use random port selection by mariadb, because I'm using spring that connects to the database on a hardcoded port in `application.properties`: 
```
spring.datasource.url=jdbc:mysql://localhost:3310/mytable 
```

```
@RunWith(SpringRunner.class)
@SpringBootTest
public abstract class BaseTest {
	//I want the embedded mariadb to run before each testclass (not before each test).
	//there should be a fresh db for each testclass.
	@BeforeClass
	public static void init() throws ManagedProcessException {
		MariaDB4jSpringService db = new MariaDB4jSpringService();
		db.setDefaultPort(3310);
		db.start();
		db.getDB().createDB("mytable");
	}
}

public class TestA extends BaseTest {
	@Test
	public void test() {
	}
}


public class TestB extends BaseTest {
	@Test
	public void test() {
	}
}

@RunWith(Suite.class)
@Suite.SuiteClasses({
		TestA.class,
		TestB.class
})
public class SuiteTest {
}
```

Exception:
```
[][] 2017-12-14 17:16:27,462 INFO c.v.e.ManagedProcess: mysqld: 
[][] 2017-12-14 17:16:29,687 ERROR c.v.e.ManagedProcess: Program [/tmp/MariaDB4j/base/bin/mysqld, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M, --basedir=/tmp/MariaDB4j/base, --datadir=/tmp/MariaDB4j/data/3310, --port=3310, --socket=/tmp/MariaDB4j.3310.sock] (in working directory /tmp/MariaDB4j/base) failed unexpectedly
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404) ~[commons-exec-1.3.jar:1.3]
	at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:48) ~[commons-exec-1.3.jar:1.3]
	at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:200) [commons-exec-1.3.jar:1.3]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[][] 2017-12-14 17:16:29,728 ERROR c.v.m.DB: failed to start mysqld
ch.vorburger.exec.ManagedProcessException: Asked to wait for "mysqld: ready for connections." from Program [/tmp/MariaDB4j/base/bin/mysqld, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M, --basedir=/tmp/MariaDB4j/base, --datadir=/tmp/MariaDB4j/data/3310, --port=3310, --socket=/tmp/MariaDB4j.3310.sock] (in working directory /tmp/MariaDB4j/base), but it already exited! (without that message in console), last 100 lines of console:
2017-12-14 17:16:27 140547705001856 [Note] /tmp/MariaDB4j/base/bin/mysqld (mysqld 10.1.13-MariaDB) starting as process 27002 ...
2017-12-14 17:16:27 140547705001856 [Note] InnoDB: Using mutexes to ref count buffer pool pages
2017-12-14 17:16:27 140547705001856 [Note] InnoDB: The InnoDB memory heap is disabled
2017-12-14 17:16:27 140547705001856 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2017-12-14 17:16:27 140547705001856 [Note] InnoDB: Memory barrier is not used
2017-12-14 17:16:27 140547705001856 [Note] InnoDB: Compressed tables use zlib 1.2.3
2017-12-14 17:16:27 140547705001856 [Note] InnoDB: Using Linux native AIO
2017-12-14 17:16:27 140547705001856 [Note] InnoDB: Using SSE crc32 instructions
2017-12-14 17:16:27 140547705001856 [Note] InnoDB: Initializing buffer pool, size = 128.0M
2017-12-14 17:16:27 140547705001856 [Note] InnoDB: Completed initialization of buffer pool
2017-12-14 17:16:27 140547705001856 [Note] InnoDB: Highest supported file format is Barracuda.
2017-12-14 17:16:27 140547705001856 [Note] InnoDB: 128 rollback segment(s) are active.
2017-12-14 17:16:27 140547705001856 [Note] InnoDB: Waiting for purge to start
2017-12-14 17:16:27 140547705001856 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.28-76.1 started; log sequence number 1616819
2017-12-14 17:16:27 140547016591104 [Note] InnoDB: Dumping buffer pool(s) not yet started
2017-12-14 17:16:27 140547705001856 [Note] Plugin 'FEEDBACK' is disabled.
2017-12-14 17:16:27 140547705001856 [Note] Server socket created on IP: '::'.
2017-12-14 17:16:27 140547705001856 [ERROR] Can't start server: Bind on TCP/IP port. Got error: 98: Address already in use
2017-12-14 17:16:27 140547705001856 [ERROR] Do you already have another mysqld server running on port: 3310 ?
2017-12-14 17:16:27 140547705001856 [ERROR] Aborting

	at ch.vorburger.exec.ManagedProcess.startAndWaitForConsoleMessageMaxMs(ManagedProcess.java:263) ~[mariaDB4j-core-2.2.3.jar:?]
	at ch.vorburger.mariadb4j.DB.start(DB.java:148) [mariaDB4j-core-2.2.3.jar:?]
	at ch.vorburger.mariadb4j.MariaDB4jService.start(MariaDB4jService.java:67) [mariaDB4j-core-2.2.3.jar:?]
	at ch.vorburger.mariadb4j.springframework.MariaDB4jSpringService.start(MariaDB4jSpringService.java:96) [mariaDB4j-core-2.2.3.jar:?]
	at BaseTest.init(BaseTest.java:23) [test-classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61) [spring-test-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70) [spring-test-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191) [spring-test-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.junit.runners.Suite.runChild(Suite.java:128) [junit-4.12.jar:4.12]
	at org.junit.runners.Suite.runChild(Suite.java:27) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137) [junit-4.12.jar:4.12]
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70) [junit-rt.jar:?]

java.lang.IllegalStateException: MariaDB4jSpringService start() failed

	at ch.vorburger.mariadb4j.springframework.MariaDB4jSpringService.start(MariaDB4jSpringService.java:99)
	at BaseTest.init(BaseTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: ch.vorburger.exec.ManagedProcessException: An error occurred while starting the database
	at ch.vorburger.mariadb4j.DB.start(DB.java:151)
	at ch.vorburger.mariadb4j.MariaDB4jService.start(MariaDB4jService.java:67)
	at ch.vorburger.mariadb4j.springframework.MariaDB4jSpringService.start(MariaDB4jSpringService.java:96)
	... 26 more
Caused by: ch.vorburger.exec.ManagedProcessException: Asked to wait for "mysqld: ready for connections." from Program [/tmp/MariaDB4j/base/bin/mysqld, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M, --basedir=/tmp/MariaDB4j/base, --datadir=/tmp/MariaDB4j/data/3310, --port=3310, --socket=/tmp/MariaDB4j.3310.sock] (in working directory /tmp/MariaDB4j/base), but it already exited! (without that message in console), last 100 lines of console:
2017-12-14 17:16:27 140547705001856 [Note] /tmp/MariaDB4j/base/bin/mysqld (mysqld 10.1.13-MariaDB) starting as process 27002 ...
2017-12-14 17:16:27 140547705001856 [Note] InnoDB: Using mutexes to ref count buffer pool pages
2017-12-14 17:16:27 140547705001856 [Note] InnoDB: The InnoDB memory heap is disabled
2017-12-14 17:16:27 140547705001856 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2017-12-14 17:16:27 140547705001856 [Note] InnoDB: Memory barrier is not used
2017-12-14 17:16:27 140547705001856 [Note] InnoDB: Compressed tables use zlib 1.2.3
2017-12-14 17:16:27 140547705001856 [Note] InnoDB: Using Linux native AIO
2017-12-14 17:16:27 140547705001856 [Note] InnoDB: Using SSE crc32 instructions
2017-12-14 17:16:27 140547705001856 [Note] InnoDB: Initializing buffer pool, size = 128.0M
2017-12-14 17:16:27 140547705001856 [Note] InnoDB: Completed initialization of buffer pool
2017-12-14 17:16:27 140547705001856 [Note] InnoDB: Highest supported file format is Barracuda.
2017-12-14 17:16:27 140547705001856 [Note] InnoDB: 128 rollback segment(s) are active.
2017-12-14 17:16:27 140547705001856 [Note] InnoDB: Waiting for purge to start
2017-12-14 17:16:27 140547705001856 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.28-76.1 started; log sequence number 1616819
2017-12-14 17:16:27 140547016591104 [Note] InnoDB: Dumping buffer pool(s) not yet started
2017-12-14 17:16:27 140547705001856 [Note] Plugin 'FEEDBACK' is disabled.
2017-12-14 17:16:27 140547705001856 [Note] Server socket created on IP: '::'.
2017-12-14 17:16:27 140547705001856 [ERROR] Can't start server: Bind on TCP/IP port. Got error: 98: Address already in use
2017-12-14 17:16:27 140547705001856 [ERROR] Do you already have another mysqld server running on port: 3310 ?
2017-12-14 17:16:27 140547705001856 [ERROR] Aborting

	at ch.vorburger.exec.ManagedProcess.startAndWaitForConsoleMessageMaxMs(ManagedProcess.java:263)
	at ch.vorburger.mariadb4j.DB.start(DB.java:148)
	... 28 more


```

**Comment by vorburger** [comment]
> Probably the server is not shut down correctly if started within @BeforeClass?

yeah, you need an `@AfterClass` which does the `db.close();`

**Comment by sddakoty** [comment]
Could you reopen this? Neither `MariaDB4jSpringService` nor `MariaDB4jSpringService.getDb()` has a `.close()` method.

I tried:
```
private MariaDB4jSpringService db;

@AfterClass
public static void closeDb() {
    db.stop();   
}
```

But that did not help either!

**Comment by vorburger** [comment]
@sddakoty sure happy to re-open this issue so you/others can look at the source code and see if a Pull Request is needed to help fix this... from a quick look, I can see that `MariaDB4jSpringService` has a `stop()` method, have you tried that?

**Comment by sddakoty** [comment]
As written in the code snippet above, I tried calling `stop()` on the maria service within `@AfterClass`. But that did not change anything.

**Comment by sddakoty** [comment]
The following solves the issue. Somehow spring reuses application context from previous testclasses, if multiple are run eg during 'mvn package'. Therefore the context must be explicit reloaded with ```@DirtiesContext```:

```
@RunWith(SpringRunner.class)
@SpringBootTest
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_CLASS)
public abstract class BaseTest {
}
```

**Comment by wangdongya** [comment]
> 以下解决了这个问题。如果多次运行，例如在'mvn package'期间，spring会以某种方式重用以前测试类的应用程序上下文。因此，上下文必须显式重新加载`@DirtiesContext`：
> 
> ```
> @RunWith(SpringRunner.class)
> @SpringBootTest
> @DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_CLASS)
> public abstract class BaseTest {
> }
> ```

I have a problem with you, but I can't solve it with your method.

**Comment by wangdongya** [comment]
Caused by: ch.vorburger.exec.ManagedProcessException: Asked to wait for "mysqld: ready for connections." from Program [/tmp/MariaDB4j/base/bin/mysqld, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M, --basedir=/tmp/MariaDB4j/base, --datadir=/tmp/MariaDB4j/data/3307, --port=3307, --socket=/tmp/MariaDB4j.3307.sock] (in working directory /tmp/MariaDB4j/base), but it already exited! (without that message in console), last 100 lines of console:
2019-02-21 16:23:44 139910310224000 [Note] /tmp/MariaDB4j/base/bin/mysqld (mysqld 10.2.11-MariaDB) starting as process 14151 ...
2019-02-21 16:23:44 139910310224000 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2019-02-21 16:23:44 139910310224000 [Note] InnoDB: Uses event mutexes
2019-02-21 16:23:44 139910310224000 [Note] InnoDB: Compressed tables use zlib 1.2.3
2019-02-21 16:23:44 139910310224000 [Note] InnoDB: Using Linux native AIO
2019-02-21 16:23:44 139910310224000 [Note] InnoDB: Number of pools: 1
2019-02-21 16:23:44 139910310224000 [Note] InnoDB: Using SSE2 crc32 instructions
2019-02-21 16:23:44 139910310224000 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2019-02-21 16:23:44 139910310224000 [Note] InnoDB: Completed initialization of buffer pool
2019-02-21 16:23:44 139909579687680 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2019-02-21 16:23:44 139910310224000 [Note] InnoDB: Highest supported file format is Barracuda.
2019-02-21 16:23:44 139910310224000 [Note] InnoDB: 128 out of 128 rollback segments are active.
2019-02-21 16:23:44 139910310224000 [Note] InnoDB: Creating shared tablespace for temporary tables
2019-02-21 16:23:44 139910310224000 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2019-02-21 16:23:44 139910310224000 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2019-02-21 16:23:44 139910310224000 [Note] InnoDB: 5.7.20 started; log sequence number 1619987
2019-02-21 16:23:44 139909339793152 [Note] InnoDB: Loading buffer pool(s) from /tmp/MariaDB4j/data/3307/ib_buffer_pool
2019-02-21 16:23:44 139910310224000 [Note] Plugin 'FEEDBACK' is disabled.
2019-02-21 16:23:44 139909339793152 [Note] InnoDB: Buffer pool(s) load completed at 190221 16:23:44
2019-02-21 16:23:44 139910310224000 [Note] Server socket created on IP: '::'.
2019-02-21 16:23:44 139910310224000 [ERROR] Can't start server: Bind on TCP/IP port. Got error: 98: Address already in use
2019-02-21 16:23:44 139910310224000 [ERROR] Do you already have another mysqld server running on port: 3307 ?
2019-02-21 16:23:44 139910310224000 [ERROR] Aborting

	at ch.vorburger.exec.ManagedProcess.startAndWaitForConsoleMessageMaxMs(ManagedProcess.java:278)
	at ch.vorburger.mariadb4j.DB.start(DB.java:153)
	... 140 more
Same error code

**Comment by wangdongya** [comment]
> 以下解决了这个问题。如果多次运行，例如在'mvn package'期间，spring会以某种方式重用以前测试类的应用程序上下文。因此，上下文必须显式重新加载`@DirtiesContext`：
> 
> ```
> @RunWith(SpringRunner.class)
> @SpringBootTest
> @DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_CLASS)
> public abstract class BaseTest {
> }
> ```

I rejoined @DirtiesContext and rewrote some of the unit tests, and found that this problem can be solved.
